services:
  prestashop:
    image: prestashop/prestashop:latest 
    ports:
      - "8082:80"
    depends_on:
      - db
      - redis
    environment:
      DB_SERVER: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWD: ${MYSQL_PASSWORD}
      DB_PREFIX: ps_
      DB_NAME: ${MYSQL_DATABASE}
      REDIS_SERVER: redis
      PS_DOMAIN: localhost:8082
      PS_INSTALL_AUTO: 1
#    volumes: # trwałe przechowywanie danych
#      - prestashop-data:/var/www/html 
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8082 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s


  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always
    
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always


volumes:
  prestashop-data:
  db-data:
  redis-data: