version: '3.8'
services:
  prestashop:
    image: prestashop:latest
    ports:
      - "89:89"
    depends_on:
      - db
      - redis


  db:
    image: percona:psmdb-6.0.6
    environment:
      MYSQL_USER: uzytkownik
      MYSQL_PASSWORD: haslo
      MYSQL_DATABASE: nazwa_bazy
    ports:
      - "3306:3306"



  redis:
    image: redis:latest
    ports:
      - "6379:6379"
